### ISSUE TITLE
Integrate MONDO subclass relationship

### ISSUE THREAD

**Issue by kevinxin90** [biothings/mydisease.info#14]

**Comment by andrewsu** [comment]
Does MONDO have relationships between classes _aside_ from `is_a` subclass relationships? Regardless, other ontologies do (e.g., http://amigo.geneontology.org/amigo/term/GO:2000731 has both `is_a` and `negatively regulates`), so we should think about a general solution that allows us to express relationships of many types.

**Comment by kevinxin90** [comment]
Parent-children relationship have been added for MONDO. Example: http://mydisease.info/v1/disease/MONDO:0016575?fields=mondo.parents,mondo.children

**Comment by kevinxin90** [comment]
MONDO Also contains following relationship info:

'http://purl.obolibrary.org/obo/BFO_0000054',
 'http://purl.obolibrary.org/obo/RO_0002162',
 'http://purl.obolibrary.org/obo/RO_0002451',
 'http://purl.obolibrary.org/obo/RO_0002573',
 'http://purl.obolibrary.org/obo/RO_0004001',
 'http://purl.obolibrary.org/obo/RO_0004020',
 'http://purl.obolibrary.org/obo/RO_0004021',
 'http://purl.obolibrary.org/obo/RO_0004022',
 'http://purl.obolibrary.org/obo/RO_0004024',
 'http://purl.obolibrary.org/obo/RO_0004025',
 'http://purl.obolibrary.org/obo/RO_0004026',
 'http://purl.obolibrary.org/obo/RO_0004027',
 'http://purl.obolibrary.org/obo/RO_0004028',
 'http://purl.obolibrary.org/obo/RO_0004029',
 'http://purl.obolibrary.org/obo/RO_0004030',
 'http://purl.obolibrary.org/obo/RO_0009501',
 'http://purl.obolibrary.org/obo/disease_shares_features_of_',
 'http://purl.obolibrary.org/obo/intersection_of',
 'http://purl.obolibrary.org/obo/mondo#disease_causes_feature',
 'http://purl.obolibrary.org/obo/mondo#disease_has_basis_in_accumulation_of',
 'http://purl.obolibrary.org/obo/mondo#disease_has_basis_in_development_of',
 'http://purl.obolibrary.org/obo/mondo#disease_has_major_feature',
 'http://purl.obolibrary.org/obo/mondo#disease_responds_to',
 'http://purl.obolibrary.org/obo/mondo#disease_shares_features_of',
 'http://purl.obolibrary.org/obo/mondo#disease_triggers',
 'http://purl.obolibrary.org/obo/mondo#part_of_progression_of_disease',
 'http://purl.obolibrary.org/obo/mondo#predisposes_towards',
 'is_a',
 'subPropertyOf'
