### ISSUE TITLE
Add Disease Ontology as a new resource for MyDisease.info

### ISSUE THREAD

**Issue by kevinxin90** [biothings/mydisease.info#15]

**Comment by kevinxin90** [comment]
Download: https://github.com/DiseaseOntology/HumanDiseaseOntology/tree/master/src/ontology

Steps:

1. _id

    MyDisease.info use MONDO as the default primary id (_id)
    - If DOID - MONDO mapping available, use MONDO as _id
      - use [batch query](https://docs.mygene.info/en/latest/doc/query_service.html#batch-queries-via-post) feature in MyDisease.info to do the mapping
      - query for "mondo.xrefs.doid" for the DOID, and retrieve "_id" from mydisease.info
    - otherwise, use DOID instead

2. Fields to extract
  - exact synonyms, type list
  - related synonyms, type list
  - is a, maybe a list (need to loop through the whole document to make sure), map to "parents" in mydisease.info
  - xrefs (type list)
    - for how to restructure xrefs, refer [here](http://mydisease.info/v1/disease/MONDO:0016575?fields=mondo.xrefs)
  - name (string)
  - definition (string)
  - doid (string)

3. Output structure

```json
{
  "_id": "MONDO:12344",
  "disease_ontology": {
     "doid": "DOID:0111648",
     "name": "ectopia lentis with ectopia of pupil",
     "definition": "An eye disease characterized by displacement of the lenses and the pupils in association with other ocular anomalies that has_material_basis_in homozygous or compound heterozygous mutation mutation in ADAMTSL4 on chromosome 1q21.2.",
    "synonyms": {
        "exact": ["..."],
        "related": ["..."]
    },
    "xrefs": {
        "mesh": "D...",
        "ncit": "...",
    },
    "parents": ["DOID:0050737", "DOID:5614"],
```

**Comment by polyg314** [comment]
Pull request at https://github.com/biothings/mydisease.info/pull/20
