### ISSUE TITLE
too many results on Disease Ontology search

### ISSUE THREAD

**Issue by andrewsu** [biothings/mydisease.info#31]
In this API query: http://mydisease.info/v1/query?q=disease_ontology.doid=DOID\:0060369&fields=disease_ontology, I expect to get one item back (*).  However, mydisease currently reports 11117 hits. The top hit is the correct item (good), but it's not clear why the others are returned.  

(*) in relatively rare cases, two or more items for one DOID may be expected since we use MONDO as the primary key...

|![image](https://user-images.githubusercontent.com/2635409/98626274-356ae900-22c6-11eb-97cc-3c92fe138ab8.png)|
|-|

**Comment by kevinxin90** [comment]
I suppose it's the query syntax:
Tried using quotes("") around DOID, seems working fine: http://mydisease.info/v1/query?q=disease_ontology.doid="DOID:0060369"&fields=disease_ontology

**Comment by andrewsu** [comment]
Got it, thanks!

**Comment by newgene** [comment]
@andrewsu also want to note that in your original query for the `q` parameter, the `:` should be used instead of `=` between the field and its value. The following query works as expected:

http://mydisease.info/v1/query?q=disease_ontology.doid:DOID\:0060369&fields=disease_ontology
