### ISSUE TITLE
add MONDO synonyms

### ISSUE THREAD

**Issue by andrewsu** [biothings/mydisease.info#4]
Full MONDO record for MONDO:0014716 Smith-Kingsmore Syndrome is at: https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0014716

The MyDisease.info record (http://mydisease.info/v1/disease/MONDO:0014716) does not list common synonyms from the MONDO record, including "MINDS syndrome" and "Smith-Kingsmore syndrome".

**Comment by kevinxin90** [comment]
This issue is fixed in 0f4716e6473244b00ab9e45ff414d67639e81d1e. Can be verify using: http://mydisease.info/v1/disease/MONDO:0014716?fields=mondo
