### ISSUE TITLE
data is being overwritten during the mondo id resolving step

### ISSUE THREAD

**Issue by colleenXu** [biothings/mydisease.info#43]
This was noticed in the HPO parser (and it's unclear if this is an issue with other parsers). The HPO parser has disease-phenotype data, with diseases having OMIM, orphanet, or decipher IDs. 

HPO annotations do not appear to have ID resolution, so **the "same" disease can have different annotations to their OMIM id compared to their orphanet ID or their decipher ID.** 

However, when the mondo ID resolving step is done, **only 1 ID's annotations are kept** (the priority list is omim first, orphanet, decipher). **This means the other data is lost/missing from the API's output.**

**Comment by andrewsu** [comment]
@colleenXu can you provide an example please?

**Comment by colleenXu** [comment]
I've shown the missing data issue [using this notebook](https://github.com/colleenXu/RegistryMetadataDev/blob/main/Showing_HPO_Annotations.ipynb) to compare the partially-processed data to what's in mydisease right now.

The code that causes some of the data to be missed (keeping annotations from only one mapped ID) is probably the if-elif-else [here](https://github.com/biothings/mydisease.info/blob/f59108a8e83cd53f18bcd2e542fb922a9d88137f/src/plugins/hpo/parser.py#L174)

However, as shown in the last section of my notebook, the solution isn't as simple as merging the records, because each disease-phenotype annotation has different references, evidence type, biocuration, frequency, etc. included with it.

**Comment by colleenXu** [comment]
@everaldorodrigo @andrewsu @newgene 

This would be a useful issue to address, but I don't know if it's in-scope for Everaldo to work on

**Comment by newgene** [comment]
assigned to @DylanWelzel to confirm with @colleenXu if this is still an issue.

**Comment by colleenXu** [comment]
Update: confirmed with Dylan that this is an issue last Friday (2/16). Dylan is working on a fix, and we discussed it more on 2/22.

**Comment by colleenXu** [comment]
@DylanWelzel asked me to review and close this issue.

Based on on our convos and a quick check of the deployed API, I think this has been successfully addressed. Here's an example: [Temtamy syndrome in MyDisease](https://mydisease.info/v1/query?q=hpo.omim:218340)
* now both the OMIM and orphanet disease mappings show up (`hpo.omim` and `hpo.orphanet` fields)
* `phenotype_related_to_disease` now contains phenotypes from both the [OMIM](https://hpo.jax.org/app/browse/disease/OMIM:218340) and [orphanet](https://hpo.jax.org/app/browse/disease/ORPHA:1777) data
    * right now, there's 59 total = 34 from OMIM + 25 from orphanet

I also see the extra adjustments:
* other fields (`clinical_course` / `inheritance` / [`clinical_modifier`](https://mydisease.info/v1/query?q=_exists_:hpo.clinical_modifier)) have been adjusted to provide all info, similar to the pheno fields. 

So I think this is good and I'm closing the issue.
