### ISSUE TITLE
BUG: Limit `parents`, `children`, `ancestors`, and `descendants` in `Mondo` document to `is_a` ontology nodes

### ISSUE THREAD

**Issue by erikyao** [biothings/mydisease.info#44]
See the discussion in [mychem.info: missing ChEBI records?](https://github.com/biothings/mychem.info/issues/83):

- [Yao's comment](https://github.com/biothings/mychem.info/issues/83#issuecomment-875862140)
- [Andrew's comment](https://github.com/biothings/mychem.info/issues/83#issuecomment-876111289)

The issue boils down to take ONLY `is_a` relationships when we try to populate fields `parents`, `ancestors`, `children`, `descendants`  by walking the ontology tree. 

The following code can be added to the `Mondo` [parser (line 35)](https://github.com/biothings/mydisease.info/blob/master/src/plugins/mondo/parser.py#L35) to fix this issue:

```python
# note that:
#     graph.edges() returns (u, v) tuple collection
#     graph.edges returns (u, v, data) triple collection
edges_to_remove = [(u, v) for (u, v, data) in graph.edges if data != "is_a"] 

# Void, in-place operation. Copy the old graph if necessary.
graph.remove_edges_from(edges_to_remove) 
```

**Comment by andrewsu** [comment]
@erikyao Just ran into this issue again -- can you look into adding / testing / deploying the fix you suggest above?  On quick glance, seems like a reasonable quick fix.  (Though I think ideally we would move those non-`is_a` relations to another key in the document, as described in my linked comment above...)

The specific example I'm looking at is http://mydisease.info/v1/disease/MONDO:0005260 for `autism`.  We incorrectly list these four children:

* "MONDO:0010726" -- [Rett syndrome](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0010726)
* "MONDO:0012081" -- [15q11q13 microduplication syndrome](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0012081)
* "MONDO:0012756" -- [proximal 16p11.2 microdeletion syndrome](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0012756)
* "MONDO:0020836" -- [autism, susceptiblity to](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0020836)

All of these are from the "term relations" part of https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0005260

![image](https://user-images.githubusercontent.com/2635409/188254564-f25de179-7444-4e50-8a78-c37a78dd5b07.png)

**Comment by andrewsu** [comment]
bumping this as a high priority fix given effect on Translator results

**Comment by erikyao** [comment]
> Though I think ideally we would move those non-is_a relations to another key in the document, as described in my linked comment above...

Looks like we did use those non-`is-a` relationships in the parser, see [here](https://github.com/biothings/mydisease.info/blob/master/src/plugins/mondo/parser.py#L86).

Solution: preserve a copy of those non-`is-a` relationships before removing them from the calculation of `parents`, `children`, `ancestors`, and `descendants`.

**Comment by erikyao** [comment]
Fixed and deployed with PR https://github.com/biothings/mydisease.info/pull/54.

See [MONDO:0005260](https://mydisease.info/v1/disease/MONDO%3A0005260?fields=mondo) for a spot check.

**Comment by andrewsu** [comment]
Looks good!
