### ISSUE TITLE
remove covid_phenotypes from MyDisease

### ISSUE THREAD

**Issue by colleenXu** [biothings/mydisease.info#45]
The [data](https://github.com/biothings/mydisease.info/tree/master/src/plugins/covid_phenotypes) is obsolete, and an updated version should be accessible to BTE through the Automat CORD19 API (smartapi registration [here](https://smart-api.info/ui/0a93684206ec6a13812ff2867a445c4e)). @andrewsu and I discussed how it didn't need to be included in MyDisease anymore...

Details:
The [covid_phenotypes info](https://mydisease.info/v1/disease/MONDO:0100096) is a old, cached version of what Automat covidphenotypes API provided - which was a hand-curated list of phenotypes that were associated with the disease COVID-19.

**Comment by zcqian** [comment]
The plan is to remove the data from builds, and then later remove the plugin entirely.

Does this plan sound fine, @newgene ?

**Comment by newgene** [comment]
@zcqian Yes, remove the data first, and we will probably still keep the code. You can label at top of this plugin code as "predicated" and pointing it to this issue.

**Comment by colleenXu** [comment]
@everaldorodrigo @andrewsu @newgene

This would be a useful issue to address, but I don't know if it's in-scope for Everaldo to work on

**Comment by colleenXu** [comment]
Update: discussed with Dylan last Friday (2/16). Note to @DylanWelzel that we'll want to remove the mapping (covid_phenotypes showing up in v1/metadata and v1/metadata/fields endpoints)

**Comment by DylanWelzel** [comment]
The newest release has removed covid_phenotypes from the v1/metadata and v1/metadata/fields endpoints. The recent PR #62 removes the code as well, @newgene is this plugin still something we want to save knowing the parser just contains hardcoded metadata? If so I can undo this change before merging the PR

```
def load_data(data_folder):
    yield {
        "_id": "MONDO:0100096",
        "covid_phenotypes": [
            {"hp": "HP:0011899", "label": "Hyperfibrinogenemia"},
            {"hp": "HP:0025143", "label": "Chills"},
            {"hp": "HP:0025439", "label": "Pharyngitis"},
            {"hp": "HP:0002027", "label": "Abdominal pain"},
            {"hp": "HP:0032141", "label": "Precordial pain"},
            {"hp": "HP:0005403", "label": "Decrease in T cell count"},
            {"hp": "HP:0002017", "label": "Nausea and vomiting"},
            {
                "hp": "HP:0005407",
                "label": "Decreased proportion of CD4-positive T cells",
            },
            {"hp": "HP:0012649", "label": "Increased inflammatory response"},
            {"hp": "HP:0003326", "label": "Myalgia"},
            {"hp": "HP:0012735", "label": "Cough"},
            {"hp": "HP:0030783", "label": "Increased serum interleukin-6"},
            {"hp": "HP:0002098", "label": "Respiratory distress"},
            {"hp": "HP:0000224", "label": "Decreased taste sensation"},
        ],
    }
 ```

**Comment by newgene** [comment]
@DylanWelzel it's ok to remove it. It was used as a temp solution, which is no longer needed.

**Comment by colleenXu** [comment]
@DylanWelzel asked me to review and close this issue. 

Based on a quick look, it looks like covid_phenotypes have been removed from the [docs](https://docs.mydisease.info/en/latest/doc/data.html) and both [metadata](https://mydisease.info/v1/metadata) [endpoints](https://mydisease.info/v1/metadata/fields). 

So I think this is good and I'm closing the issue.
